### ISSUE TITLE
remotePath to parent folder

### ISSUE THREAD

**Issue by DmitryEfimenko** [sindresorhus/gulp-ftp#29]
I have the following folder structure on my ftp:
```
...
root
usr
   local
      www
...
```
The following code will get me into `root` folder:
```
ftp({
      host: '***',
      user: '***',
      pass: '***',
}
```
However, I need to deploy into `usr/local/www`, which is why I specify that in `remotePath`:
```
remotePath: '../usr/local/www'
```
This results in files copied into the correct folder, but also new folders created under folder `root`:
```
...
root
   usr
      local
         www
usr
   local
      www
...
```
Am I doing something wrong?

EDIT: Actually files are only copied successfully to the existing folders (in my case it was folder `www`)

**Comment by sindresorhus** [comment]
@morris Can you make sure [`vinyl-ftp`](https://github.com/morris/vinyl-ftp) handles this?

**Comment by sindresorhus** [comment]
@DmitryEfimenko This will be deprecated soon in favor of [`vinyl-ftp`](https://github.com/morris/vinyl-ftp). Can you open an issue there instead if it has the same problem?
