### ISSUE TITLE
Delete remote files

### ISSUE THREAD

**Issue by IVisualDev** [sindresorhus/gulp-ftp#30]
very nice and easy gulp plugin. would be nice to have an option to delete the remote files (cleanup) before uploading.

**Comment by sindresorhus** [comment]
This plugin is soon going to be deprecated in favor of https://github.com/morris/vinyl-ftp

Open an issue there instead ;)

**Comment by bartvanderwal** [comment]
Well I would like this too! And I couldn't get vinyl-ftp running, while gulp-ftp worked out of the box...

Would you reconsider? :)

**Comment by sindresorhus** [comment]
No, this task is deprecated.
