### ISSUE TITLE
Use all declared paths

### ISSUE THREAD

**Issue by pyrsmk** [sindresorhus/gulp-ftp#32]
Hi!

I'm facing a disrupting problem with the plugin. I want to specify several paths and excluding some other paths, all at once like : 

```ftp
gulp.task('deploy', ['css', 'js', 'images'], function(){

	var config = require('./config/ftp.json');

	return gulp.src([
			'cache/*',
			'!cache/*/**',
			'config/*',
			'!config/ftp.json',
			'components/',
			'images/',
			'js/*',
			'!js/node_modules',
			'!js/ender*',
			'js/ender.min.js',
			'pages/',
			'vendor/',
			'.htaccess',
			'define.php',
			'index.php'
		])
		.pipe(plumber())
		.pipe(cache('ftp'))
		.pipe(ftp(prod ? config.prod : config.dev))
		.pipe(noop());

});
```

But gulp-ftp seems to only upload some random files (in my case, the files at the root, and one file in config/).

Maybe I misunderstood something ^^

**Comment by sindresorhus** [comment]
Can you use `gulp-debug` to make sure the files actually come through?

**Comment by pyrsmk** [comment]
I switched to vinyl-ftp that better matches my needs.
But I can debug this, I need to reimplement it in my gulp file.

**Comment by sindresorhus** [comment]
@pyrsmk Nah, don't bother. This will hopefully soon be deprecated in favor of vinyl-ftp :)
