### ISSUE TITLE
Should be a vinyl-ftp module instead of a gulp plugin

### ISSUE THREAD

**Issue by phated** [sindresorhus/gulp-ftp#4]
This type of module should be a vinyl adapter layer, like vinyl-fs but over FTP, this would allow to use src/dest/watch against FTP and plug in any gulp plugins.

/cc @Contra

**Comment by morris** [comment]
I was working on this as I wanted fast deployment with Gulp. The dest stream turned out quite good, very fast, although I'm not too sure about the API. src and watch are still missing. Let me know if you think this is going the right way:

https://github.com/morris/vinyl-ftp

**Comment by contra** [comment]
@morris You shouldn't need to use the `new` keyword or construct anything ahead of time. Keep a connection pool cached instead and take a connection option as the first argument

@phated @sindresorhus Thoughts?

```js
var ftp = vinylFtp.create(conn);

.pipe(ftp.dest(folder))
```

vs

```js
.pipe(ftp.dest(conn, folder))
```

**Comment by morris** [comment]
@contra Yes, definitely one of the things I wasn't sure about. The current implementation caches a lot more than connections though (MLSD for example), and I'm not sure if that plays nicely with an API like

  .pipe( ftp.newer( conn, folder ) )
  .pipe( ftp.dest( conn, folder ) ) // reuses all MLSD
  .pipe( ftp.mode( conn, folder, mode ) ) // reuses all MLSD

Now if you have another FTP server involved, the package would have to decide which connection pool/cache to check, which would probably force IDs on the connections (think same host, different user; hard to decide). Therefore it seemed more elegant to me when wrapped into an object (connection credentials, connection pool, cached resources).

In any case, dropping 'new' in favor of create() is a good idea though, much more future-proof :+1:

**Comment by phated** [comment]
I think the options for the ftp connection should just go in the options object of `src`/`dest`/`watch`  I'm also wondering if `src` could set a listener for `pipe` (like https://github.com/mikeal/response/blob/master/index.js#L40) that passes the ftp connection in if the options aren't already set

**Comment by morris** [comment]
I still don't think this is a good idea. It makes the API less obvious and has no straight-forward implementation:

- What is cached when and where?
- What if I need a fresh connection pool with an empty cache? With the current API, I just create a new instance.
- The API would look functional but has to manage a lot of state under the hood. Object orientation is more suitable in this situation.
- With multiple servers, it's not trivial to implement a distinction between them.

(This is probably not a valid argument, but [vinyl-s3](https://www.npmjs.com/package/vinyl-s3) also constructs ahead of time.)

A lot of this follows from the fact that vinyl-fs does not need state (there's only one filesystem) but FTP does. Maybe `dest` really is misleading in the first place. It does not exactly behave like in vinyl-fs (input files are passed through). `upload` and later `download` might be more suitable.

**Comment by phated** [comment]
Passing the config to each method doesn't maintain state.  My other idea was just a thought I've had in the past.

**Comment by sindresorhus** [comment]
@morris How close are you to finishing `vinyl-ftp`? I'd like to deprecate `gulp-ftp`.

**Comment by morris** [comment]
I will add a new release containing `src` in a few days. Everything is working so far but it still needs a better test suite.

**Comment by morris** [comment]
Just released [v0.3.0](https://www.npmjs.com/package/vinyl-ftp) with `src`. Tests are still very rough, will get to write more soon. #29 should not be an issue, but I will add a special test case for that one.

**Comment by sindresorhus** [comment]
@morris What's the status of `vinyl-ftp`?

**Comment by morris** [comment]
Using it day in, day out, and it seems some more people do as well. There's a few API weaknesses I'm currently addressing, and the different server behaviors are hard to test, but other than that it's quite stable.

**Comment by sindresorhus** [comment]
Alright. This task is now officially deprecated in favor of yours @morris. Be a good maintainer ;)
